language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

# faster builds on new travis setup not using sudo
sudo: false

before_install:
 - cd ./tests/data/ci && chmod +x *.sh

install:
  - "./tests/data/ci/_composer_install.sh"
  - mkdir -p build/logs
  - "./tests/data/ci/start-ci.sh $ORIENTDB_VERSION"

cache:
  directories:
  - ./tests/data/ci/environment/orientdb-community-$ORIENTDB_VERSION
  - ./vendor

before_cache:
- ls -la ./tests/data/ci/environment/
- rm -f ./tests/data/ci/environment/orientdb-community-$ORIENTDB_VERSION/log/*
- rm -rf ./tests/data/ci/environment/orientdb-community-$ORIENTDB_VERSION/databases/*

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
    fi


script:
 - ./vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      php ./vendor/bin/coveralls -v
    fi

env:
  - ORIENTDB_VERSION=2.1.13
  - ORIENTDB_VERSION=2.1.12
  - ORIENTDB_VERSION=2.1.11
  - ORIENTDB_VERSION=2.1.10
  - ORIENTDB_VERSION=2.0.18
  - ORIENTDB_VERSION=2.0.17
  - ORIENTDB_VERSION=2.0.16
  - ORIENTDB_VERSION=2.0.15
  - ORIENTDB_VERSION=1.7.10
