language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

# faster builds on new travis setup not using sudo
sudo: false

install:
  - travis_retry composer self-update && composer --version
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - travis_retry composer global require fxp/composer-asset-plugin:"^1.1.0" --no-plugins
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
  - mkdir -p build/logs
  - "./tests/data/ci/start-ci.sh $ORIENTDB_VERSION"

cache:
  directories:
  - ./tests/data/ci/environment/orientdb-community-$ORIENTDB_VERSION
  - ./vendor

before_cache:
- ls -la ./tests/data/ci/environment/
- rm -f ./tests/data/ci/environment/orientdb-community-$ORIENTDB_VERSION/log/*
- rm -rf ./tests/data/ci/environment/orientdb-community-$ORIENTDB_VERSION/databases/*

script:
 - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then
      php ./vendor/bin/coveralls -v
    fi

env:
  - ORIENTDB_VERSION=2.1.13
